server:
  port: ${APP_PORT:8080}

spring:
  application:
    name: split-net
  jpa:
    database: POSTGRESQL
    show-sql: true
    hibernate:
      ddl-auto: update
    datasource:
      platform: postgres
      url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:split-name}
      username: ${DB_USER:postgres}
      password: ${DB_PASS:postgres}
      driverClassName: org.postgresql.Driver

wg:
  interface: wg0